[project]
name = "hci-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.5.2",
    "fastapi[standard]>=0.115.12",
    "markdown>=3.8",
    "openai>=1.77.0",
]
