[project]
name = "hci-project-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "motor>=3.7.0",
    "openai>=1.72.0",
]
